language: objective-c
osx_image: xcode7

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
  - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="Thongs-Example" SDK=iphonesimulator9.0

xcode_sdk: iphonesimulator9.0

before_install: 
- gem install cocoapods

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild -workspace Example/Thongs.xcworkspace -scheme Thongs-Example -sdk iphonesimulator 
	-configuration ONLY_ACTIVE_ARCH=NO test | xcpretty -c
#- xcodebuild test -workspace Example/Thongs.xcworkspace -scheme "$SCHEME"" -sdk "$SDK" -destination "$DESTINATION"
#	-configuration ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- pod lib lint --quick
