language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 6" SDK=iphonesimulator10.0 WORKSPACE=Example/Thongs.xcworkspace

before_install:
- gem install cocoapods

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -workspace "$WORKSPACE" -scheme Thongs-Example -sdk "$SDK" -destination "$DESTINATION" build test | xcpretty -c
- pod lib lint --quick
