# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7

env:
  - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="Thongs-Example" SDK=iphonesimulator9.0

xcode_sdk: iphonesimulator9.0

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install: 
- gem install cocoapods
# - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- set -o pipefail && xcodebuild test -workspace Example/Thongs.xcworkspace -scheme Thongs-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
#- xcodebuild test -workspace Example/Thongs.xcworkspace -scheme "$SCHEME"" -sdk "$SDK" -destination "$DESTINATION"
#	-configuration ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- pod lib lint --quick
